### ISSUE TITLE
terminate called after throwing an instance of 'thrust::system::system_error'

### ISSUE THREAD

**Issue by francoisruty** [BachiLi/redner#61]
I'm running tutorials/04_fast_deferred_rendering.py with another .obj than teapot.obj, and I'm getting at some point in the training loop:

iteration: 103
Scene construction, time: 0.04477 s
Forward pass, time: 0.00790 s
loss: 239.15292358398438
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  device free failed: an illegal memory access was encountered
Aborted (core dumped)

has this error been seen before?

**Comment by francoisruty** [comment]
I installed redner with instruction there:
https://github.com/BachiLi/redner/wiki/Installation
(docker gpu build)

**Comment by BachiLi** [comment]
This can be anything. If you can give me the obj file that causes the error for testing it would be very helpful.

**Comment by francoisruty** [comment]
Hi, here is attached obj and python code to reproduce the issue
[case.zip](https://github.com/BachiLi/redner/files/3637303/case.zip)

In the gpu docker container,
cd /app/tutorials  (put there the .zip content)
python ./zz_test.py

and at some point in the training loop you should encounter the issue

**Comment by francoisruty** [comment]
NOTE: I don't have the problem when running this code with this obj in docker CPU container

**Comment by BachiLi** [comment]
I can't reproduce this unfortunately. What is your GPU? Can you do `cuda-memcheck python ./zz_test.py` and show me the log?

**Comment by BachiLi** [comment]
Wait, I finally was able to reproduce this after ~10 runs. Stay tuned...

**Comment by francoisruty** [comment]
awesome! FYI I'm on a GTI 1080

**Comment by BachiLi** [comment]
I think I found the issue. https://github.com/BachiLi/redner/commit/fa02b6bf3825843f170238038bfacfb0d515bf46 should fix it. There is a buffer overrun issue in edge sampling when the output channel doesn't contain radiance. Unfortunately this means that the deferred rendering code was never properly working : (
Thanks a lot for reporting this.

**Comment by francoisruty** [comment]
awesome, thanks!
Btw I sent you an email to your MIT address to ask a few questions about contributing, let me know!

**Comment by BachiLi** [comment]
I didn't receive the email. Maybe send it again or send to tzumao@berkeley.edu?

**Comment by francoisruty** [comment]
ok, sending it now!

**Comment by francoisruty** [comment]
ok so the issue is solved, confirmed on my side, I pulled your latest commits and it solved the problem.
Thanks!
